/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AceEditor: typeof import('./src/components/Editor/AceEditor.vue')['default']
    AIPanel: typeof import('./src/components/AIPanel.vue')['default']
    AIPanelHost: typeof import('./src/components/__tests__/AIPanelHost.vue')['default']
    AnimationList: typeof import('./src/components/AnimationList.vue')['default']
    AnimationSettingModal: typeof import('./src/components/AnimationSettingModal.vue')['default']
    Area: typeof import('./src/components/Editor/Area.vue')['default']
    CanvasAttr: typeof import('./src/components/CanvasAttr.vue')['default']
    CommandTimeline: typeof import('./src/components/CommandTimeline.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList.vue')['default']
    ComponentWrapper: typeof import('./src/components/Editor/ComponentWrapper.vue')['default']
    ContextMenu: typeof import('./src/components/Editor/ContextMenu.vue')['default']
    Editor: typeof import('./src/components/Editor/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    EventList: typeof import('./src/components/EventList.vue')['default']
    Grid: typeof import('./src/components/Editor/Grid.vue')['default']
    MarkLine: typeof import('./src/components/Editor/MarkLine.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    NodeRenderer: typeof import('./src/components/Editor/NodeRenderer.vue')['default']
    PageManager: typeof import('./src/components/PageManager.vue')['default']
    Preview: typeof import('./src/components/Editor/Preview.vue')['default']
    PreviewNodeRenderer: typeof import('./src/components/Editor/PreviewNodeRenderer.vue')['default']
    RealTimeComponentList: typeof import('./src/components/RealTimeComponentList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shape: typeof import('./src/components/Editor/Shape.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    VersionHistory: typeof import('./src/components/VersionHistory.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
